### PR TITLE
PR: Introduced Tree menu

### PR DESCRIPTION
**Pull request by OldIMP**
We added 2 new methods addTreeItem() that allow to add menu items in a tree structure. Vaadin version had to be upgraded to 8.1.6.

Cheers,
OldIMP

---
This change is [Reviewable](https://reviewable.io/reviews/tsuoanttila/sidemenu-addon/14)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Thanks for the PR, I'll try to take time tomorrow to check it out and actually test it a bit manually. Code itself seems to be pretty fine!

---

Reviewed 1 of 5 files at r1, 1 of 4 files at r3, 3 of 4 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java, line 107 at r5](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-L-lNAnaC17JHAqPqOGK:-L-lNAnaC17JHAqPqOGL:b-40f3iw) ([raw file](https://github.com/tsuoanttila/sidemenu-addon/blob/6bb60eef3776c45c41e6f831e4be27034ab6e6a9/sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java#L107)):*
> ```Java
>     private final MenuBar userMenu = new MenuBar();
> 
>     private final Tree<String> treeMenu = new Tree<>();
> ```

This could be quite easily improved to make it possible to use the same name on different depths by using a class that stores a String.

---

*[sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java, line 147 at r5](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-L-lMNh_oX2eaGo8f7E1:-L-lMNh_oX2eaGo8f7E2:bchbsdk) ([raw file](https://github.com/tsuoanttila/sidemenu-addon/blob/6bb60eef3776c45c41e6f831e4be27034ab6e6a9/sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java#L147)):*
> ```Java
>         menuArea.addComponent(userMenu);
> 
>         Button valoMenuToggleButton = new Button("Menu", (ClickListener) event -> {
> ```

Shouldn't need the explicit cast to ClickListener

---

*[sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java, line 218 at r5](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-L-lM_gW5WvLKG5kXsco:-L-lM_gW5WvLKG5kXscp:bf1nqqp) ([raw file](https://github.com/tsuoanttila/sidemenu-addon/blob/6bb60eef3776c45c41e6f831e4be27034ab6e6a9/sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java#L218)):*
> ```Java
>      */
>     public MenuRegistration addMenuItem(String text, Resource icon, final MenuClickHandler handler) {
>         Button button = new Button(text, (ClickListener) event -> {
> ```

Should not need explicit cast to ClickListener

---

*[sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java, line 229 at r5](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-L-lPlPbWCjem5AWq1x-:-L-lPlPcGA17moL9wTCb:b-ll7l04) ([raw file](https://github.com/tsuoanttila/sidemenu-addon/blob/6bb60eef3776c45c41e6f831e4be27034ab6e6a9/sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java#L229)):*
> ```Java
> 
>     /**
>      * Add a root tree item to the menu. If it already exists, nothing happens and the existing {@link MenuRegistration} is returned
> ```

The fact that you don't know that your tree didn't get the new item since there's already an item with the same text is a bit problematic. Having no clue that the piece of code that happily worked only lost your new click listener completely can be nasty to debug. Yes, the JavaDoc has a warning for this, but still.

---

*[sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java, line 235 at r5](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-L-lO0uA8QiYyEcjswU3:-L-lO0uA8QiYyEcjswU4:bg34ejl) ([raw file](https://github.com/tsuoanttila/sidemenu-addon/blob/6bb60eef3776c45c41e6f831e4be27034ab6e6a9/sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java#L235)):*
> ```Java
>      * @return MenuRegistration of the added item
>      */
>     public MenuRegistration addTreeItem(String rootItem, MenuClickHandler clickHandler) {
> ```

why doesn't this just call `addTreeItem(null, rootItem, clickHandler)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-:-L-lM4UvqIx1UR9d5eZr:b-84r8vn)*

**Comment by OldIMP** [comment]
Thanks for the review & suggestions!

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java, line 107 at r5](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-L-lNAnaC17JHAqPqOGK:-L-lT-alvOxOtQLCQXXL:bu2s7xx) ([raw file](https://github.com/tsuoanttila/sidemenu-addon/blob/6bb60eef3776c45c41e6f831e4be27034ab6e6a9/sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java#L107)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This could be quite easily improved to make it possible to use the same name on different depths by using a class that stores a String.
</blockquote></details>

For the first draft we just used String instead of generic types. It'll be great if we can also integrate MenuClickHandler into MenuRegistration, then we can save both them into the TreeData type. But that's a major API change decision that we didn't want to make

---

*[sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java, line 229 at r5](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-L-lPlPbWCjem5AWq1x-:-L-lTgU0xeh3V23mNl_0:bdmaeqd) ([raw file](https://github.com/tsuoanttila/sidemenu-addon/blob/6bb60eef3776c45c41e6f831e4be27034ab6e6a9/sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java#L229)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

The fact that you don't know that your tree didn't get the new item since there's already an item with the same text is a bit problematic. Having no clue that the piece of code that happily worked only lost your new click listener completely can be nasty to debug. Yes, the JavaDoc has a warning for this, but still.
</blockquote></details>

We can also happily overwrite the existing menu item or throw an exception

---

*[sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java, line 235 at r5](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-L-lO0uA8QiYyEcjswU3:-L-lTrrIwMZgZf7rx2O_:b-40s39k) ([raw file](https://github.com/tsuoanttila/sidemenu-addon/blob/6bb60eef3776c45c41e6f831e4be27034ab6e6a9/sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java#L235)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

why doesn't this just call `addTreeItem(null, rootItem, clickHandler)`?
</blockquote></details>

As a shortcut for root items :) Don't like to write nulls all the time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-:-L-lUA0raBC7u-OsGYi8:bpxy0bg)*

**Comment by OldIMP** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java, line 147 at r5](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-L-lMNh_oX2eaGo8f7E1:-L0EF0XV9c8bXV9ZTV1c:b-896fix) ([raw file](https://github.com/tsuoanttila/sidemenu-addon/blob/6bb60eef3776c45c41e6f831e4be27034ab6e6a9/sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java#L147)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Shouldn't need the explicit cast to ClickListener
</blockquote></details>

Done.

---

*[sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java, line 218 at r5](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14#-L-lM_gW5WvLKG5kXsco:-L0EF3-dpEzNYaZjnKYZ:b-896fix) ([raw file](https://github.com/tsuoanttila/sidemenu-addon/blob/6bb60eef3776c45c41e6f831e4be27034ab6e6a9/sidemenu-addon/src/main/java/org/vaadin/teemusa/sidemenu/SideMenu.java#L218)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should not need explicit cast to ClickListener
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/tsuoanttila/sidemenu-addon/14)*

**Pull request merged**
