### PR TITLE
updated to vaadin 8. Tested demo with local jetty to validate changes…

### PR DESCRIPTION
**Pull request by dcosio-ct**
… work

### CODE REVIEW

**Comment by StevNash1337** [comment]
I hope he will fix it soon! I've got the same problem like you @dcosio-ct

**Comment by dcosio-ct** [comment]
This is really a migration issue since the ui package has changed between Vaadin 7 and Vaadin 8. So I end up just building my own jar after I did the fix locally.

**Comment by lorthirk** [comment]
hi @tsuoanttila,

Do you have something against this PR? It would be great if you could merge it and release a new version!

**Comment by tsuoanttila** [comment]
My apologies, I have completely missed this pull request. I will test it out asap.

**Comment by tsuoanttila** [comment]
Once again thanks to @dcosio-ct for PR, and @lorthirk for reminding me! @StevNash1337 it's out now.

**Pull request merged**
